In [2]:
import numpy as np

In [15]:
!ls /media/elijah/NewDisk/diploma/Simultaneous\ EEG-fMRI/BIDS_dataset_MRI

dataset_description.json  sub-003  sub-009  sub-015  task-eoec_bold.json
participants.json	  sub-004  sub-010  sub-016  task-rest_bold.json
participants.tsv	  sub-005  sub-011  sub-017
README			  sub-006  sub-012  sub-018
sub-001			  sub-007  sub-013  sub-019
sub-002			  sub-008  sub-014  sub-020

In [35]:
import os
from bids import BIDSLayout
from nilearn import plotting, image
import nibabel as nib

# Указываем путь к BIDS датасету
bids_path = "/home/elijah/diploma_data/ds004791-download"

# Инициализируем BIDS Layout
layout = BIDSLayout(bids_path, validate=True)

# Получаем список всех NIfTI файлов в датасете
nifti_files = layout.get(extension='nii.gz', return_type='file')

# Визуализируем каждый NIfTI файл
for nifti_file in nifti_files:
    plotting.plot_stat_map(nifti_file, bg_img=False, threshold=3, display_mode='ortho', cut_coords=(X, Y, Z), title="Statistical map")
    # Интерактивная визуализация
    # plotting.view_img(first_timepoint, bg_img=False, title="First timepoint")
    plotting.show()

NameError: name 'X' is not defined

In [39]:
layout.to_df()

entity,path,datatype,extension,run,subject,suffix,task
0,/home/elijah/diploma_data/ds004791-download/da...,NaN,.json,NaN,NaN,description,NaN
1,/home/elijah/diploma_data/ds004791-download/pa...,NaN,.tsv,NaN,NaN,participants,NaN
2,/home/elijah/diploma_data/ds004791-download/su...,anat,.json,NaN,0011,T1w,NaN
3,/home/elijah/diploma_data/ds004791-download/su...,anat,.nii.gz,NaN,0011,T1w,NaN
4,/home/elijah/diploma_data/ds004791-download/su...,func,.json,01,0011,bold,arithmetic
...,...,...,...,...,...,...,...
1322,/home/elijah/diploma_data/ds004791-download/su...,func,.json,02,1532,bold,vswm
1323,/home/elijah/diploma_data/ds004791-download/su...,func,.nii.gz,02,1532,bold,vswm
1324,/home/elijah/diploma_data/ds004791-download/su...,func,.tsv,02,1532,events,vswm
1325,/home/elijah/diploma_data/ds004791-download/RE...,NaN,NaN,NaN,NaN,NaN,NaN
1326,/home/elijah/diploma_data/ds004791-download/CH...,NaN,NaN,NaN,NaN,NaN,NaN